-- MySQL/MariaDB-based Mobilhotell
-- No manual migration is required.
-- Schema is auto-created on first request by db.php.
-- Database name: mobilhotell
-- Admin/diagnostic queries: sql/admin_queries.sql
